services:
  cip68_webapp:
    container_name: cip68_webapp
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3785:3000"
    depends_on:
      - postgres
    networks:
      - cip68
    restart: always

networks:
  cip68:
    driver: bridge
