import type { Metadata } from 'next';
import { Lexend as FontSans } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '@/utils';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const fontSans = FontSans({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(fontSans.className, 'antialiased')}>{children}</body>
        </html>
    );
}
