import React, { ReactNode } from "react";
import type { Metadata } from "next";
import { Lexend as FontSans } from "next/font/google";
import { cn } from "@/utils";
import "@/styles/globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const fontSans = FontSans({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

type Props = {
    children: ReactNode;
};

const RootLayout = function ({ children }: Readonly<Props>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(fontSans.className, "antialiased")}>{children}</body>
        </html>
    );
};

export default RootLayout;
